// Privated Credentials
const APP_PORT = process.env.APP_PORT || 8080;
const ENVIRONMENT = process.env.ENVIRONMENT;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

const ENV_VARS = {
  PORT: APP_PORT,
  ENV: ENVIRONMENT,
  GEMINI_API_KEY: GEMINI_API_KEY,
};

export { ENV_VARS };

// SERVER RESPONSE
const BAD_REQUEST_STATUS_CODE = 400;
const UNAUTHORIZED_REQUEST_STATUS_CODE = 401;
const CONFLICT_REQUEST_STATUS_CODE = 409;

const RESPONSE_MESSAGES = {
  CODES: {
    BAD_REQUEST: BAD_REQUEST_STATUS_CODE,
    UNAUTHORIZED: UNAUTHORIZED_REQUEST_STATUS_CODE,
    CONFLICT: CONFLICT_REQUEST_STATUS_CODE,
  },
};

const ZOD_REQUIRED_ERR = "{field} is required";

export { RESPONSE_MESSAGES, ZOD_REQUIRED_ERR };
